#! /bin/sh
sxhkd &

# If HDMI-1 connected, split workspaces to both monitors
if [ "$(xrandr | grep "HDMI-1 connected")" ]
then
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor eDP-1 -d 6 7 8 9 10

else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi
xrandr --auto
xrandr --output eDP --set TearFree on

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


# Sometimes when using an external monitor that is larger than the base laptop
# screen size, padding would be applied to make the nodes the size of the
# laptop resolution - we don't want that, as the nodes should fill out the
# entire height/width of the monitor, so we set all padding to 0.
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc rule -a urxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc rule -a SDEditor state=floating

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true
bspc config focused_border_color \#28282j

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill --randomize ~/Images/Wallpapers/*
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/Images/gods_die_too.png
# ------- Autostart apps ------
# Picom
picom --xrender-sync-fence &
# Dunst
dunst &
# network-manager-applet
nm-applet &
# Fcitx5
fcitx5 &


# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
libinput-gestures-setup start
# Xinput configs (touchpad)
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0

export _JAVA_AWT_WM_NONREPARENTING=1
